In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
data = pd.read_csv('./data/data.csv')

In [7]:
data.head()

First Sem   Second Sem   -
0  34.623660    78.024693   0
1  30.286711    43.894998   0
2  35.847409    72.902198   0
3  60.182599    86.308552   1
4  79.032736    75.344376   1

In [14]:
data.columns

Index(['First Sem', ' Second Sem', ' -'], dtype='object')

In [17]:
data.drop(' -', axis=1, inplace=True)

In [18]:
data

First Sem   Second Sem
0   34.623660    78.024693
1   30.286711    43.894998
2   35.847409    72.902198
3   60.182599    86.308552
4   79.032736    75.344376
..        ...          ...
95  83.489163    48.380286
96  42.261701    87.103851
97  99.315009    68.775409
98  55.340018    64.931938
99  74.775893    89.529813

[100 rows x 2 columns]

In [21]:
X, y = data['First Sem'], data[' Second Sem']

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [27]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [28]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, BaggingRegressor, ExtraTreesRegressor

In [30]:
model = RandomForestRegressor()
model.fit(X_train.reshape(-1, 1), y_train)

RandomForestRegressor()

In [37]:
preds = model.predict(X_test.reshape(-1, 1))

In [43]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [46]:
# Predict the next semester marks using the test set
y_pred = model.predict(X_test.reshape(-1,1))

# Calculate regression metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [47]:
mae, mse, r2

(20.244510791577756, 558.3345170446407, -0.6539598173870533)

In [50]:
def train(model):
    model = model()
    model.fit(X_train.reshape(-1, 1), y_train)
    # Predict the next semester marks using the test set
    y_pred = model.predict(X_test.reshape(-1,1))
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mae, mse, r2, model, y_pred

In [51]:
train(AdaBoostRegressor)

(17.443580336123947,
 376.2063252627054,
 -0.1144396881011911,
 AdaBoostRegressor(),
 array([68.5205343 , 64.70479784, 68.5205343 , 79.77591261, 68.5205343 ,
        73.53797242, 68.5205343 , 65.74588676, 68.5205343 , 66.58797413,
        68.5205343 , 64.70479784, 66.58797413, 79.77591261, 73.53797242,
        68.5205343 , 61.51308134, 66.58797413, 65.74588676, 64.70479784,
        64.70479784, 79.77591261, 62.15630757, 62.15630757, 66.58797413]))

In [52]:
train(BaggingRegressor)

(19.568761637736138,
 579.3090818711003,
 -0.7160929765436281,
 BaggingRegressor(),
 array([87.47967067, 76.92557693, 88.52547252, 73.38376689, 73.1736126 ,
        84.63586612, 72.5230317 , 60.0673958 , 88.52547252, 45.76803573,
        69.04597665, 73.98585773, 45.76803573, 68.83545456, 75.38615336,
        69.04597665, 42.26786331, 42.65885187, 47.66319355, 96.25272524,
        55.14151003, 68.83545456, 64.71082839, 63.01127292, 47.58897051]))

In [53]:
train(ExtraTreesRegressor)

(22.53392962445183,
 743.8206367054771,
 -1.2034271693715652,
 ExtraTreesRegressor(),
 array([82.24335223, 78.22505101, 88.51121442, 74.30887325, 81.21172865,
        88.67409604, 81.54323632, 56.82903947, 86.90970779, 44.22310156,
        66.06281927, 75.50392667, 42.16318933, 95.26985324, 87.57417142,
        66.95183508, 42.42094991, 42.22158114, 42.50840944, 96.1545986 ,
        48.0357221 , 94.70773915, 57.62778079, 73.41088688, 42.95036568]))

In [54]:
!pip install joblib

In [55]:
mae, mse, r2, model, y_pred = train(AdaBoostRegressor)

In [56]:
from joblib import dump, load

# Save the model to a file
dump(model, 'model.joblib')

['model.joblib']

In [57]:
# Load the model from the file
loaded_model = load('model.joblib')

In [60]:
loaded_model.predict(X_test.reshape(-1,1))

array([82.05164099, 68.62700578, 82.05164099, 68.62700578, 73.0933646 ,
       69.96220652, 64.4928154 , 65.30568994, 82.05164099, 62.97914975,
       64.4928154 , 65.18829887, 62.97914975, 73.0933646 , 69.96220652,
       64.4928154 , 41.28514227, 62.97914975, 68.62700578, 73.0933646 ,
       64.04022573, 73.0933646 , 65.30568994, 65.30568994, 62.97914975])